# PDFMate smoke sample generator (ASCII only)
# Creates sample.docx (Word COM) and sample.xlsx (Excel COM) in -OutDir
param([Parameter(Mandatory=$true)][string]$OutDir)
$ErrorActionPreference = 'Stop'

$w = New-Object -ComObject Word.Application
$w.Visible = $false
$w.DisplayAlerts = 0
try {
  $doc = $w.Documents.Add()
  $sel = $w.Selection
  $sel.TypeText('PDFMate Smoke Sample Document')
  $sel.TypeParagraph()
  $sel.TypeText('Page one content generated by MS Word COM engine.')
  $sel.InsertBreak(7)
  $sel.TypeText('Page two content for merge verification.')
  $doc.SaveAs2((Join-Path $OutDir 'sample.docx'), 16)
  $doc.Close(0)
} finally {
  $w.Quit()
}

$e = New-Object -ComObject Excel.Application
$e.Visible = $false
$e.DisplayAlerts = $false
try {
  $wb = $e.Workbooks.Add()
  $ws = $wb.Worksheets.Item(1)
  $ws.Cells.Item(1,1) = 'Quarter'
  $ws.Cells.Item(1,2) = 'Revenue'
  $ws.Cells.Item(2,1) = 'Q1'
  $ws.Cells.Item(2,2) = 1024
  $ws.Cells.Item(3,1) = 'Q2'
  $ws.Cells.Item(3,2) = 2048
  $wb.SaveAs((Join-Path $OutDir 'sample.xlsx'), 51)
  $wb.Close($false)
} finally {
  $e.Quit()
}
Write-Output 'OK'
